config/routes.rb
Rails.application.routes.draw do
    #get 'home/zipcode'
    root 'home#index'
    post 'zipcode' => 'home#zipcode'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      require 'net/http'
      require 'json'

      @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=82007&distance=0&API_KEY=A3E9205E-A146-4691-B947-F802E7DE5C12'
      @uri = URI(@url)
      @response = Net::HTTP.get(@uri)
      @output = JSON.parse(@response)

      # check for emprty return result
      if @output.empty?
          @final_output = "Error"
      elsif !@output
          @final_output = "Error"
      else
           @final_output = @output[0]['AQI']
      end

      if @final_output == "Error"
          @api_color = "silver"
      elsif @final_output <= 50
          @api_color ="green"
          @api_description = "Good (0-50)"
      elsif @final_output >= 51 && @final_output <=100
          @api_color ="yellow"
          @api_description = "Moderate (51-100)"
      elsif @final_output >= 101 && @final_output <=150
          @api_color ="orange"
          @api_description = "Unhealthy for Sensitive Groups (USG) (101-150)"
      elsif @final_output >= 151 && @final_output <=200
          @api_color ="red"
          @api_description = "Unhealthy (151-200)"
      elsif @final_output >= 201 && @final_output <300
          @api_color ="purple"
          @api_description = "Very Unhealthy (201-300)"
      else @final_output >= 301 && @final_output <=500
          @api_color ="magenta"
          @api_description = "Hazardous 300-500)"

      end
  end

  def zipcode
      @zip_query = params[:zipcode]

      if params[:zipcode] == ""
          @zip_query = "Hey you forgot to enter a zipcode"
      elsif params[:zipcode]
        # do API stuff
        require 'net/http'
        require 'json'

        @url = 'https://www.airnowapi.org/aq/observation/zipCode/current/?format=application/json&zipCode=' + @zip_query.to_s + '&distance=0&API_KEY=A3E9205E-A146-4691-B947-F802E7DE5C12'
        @uri = URI(@url)
        @response = Net::HTTP.get(@uri)
        @output = JSON.parse(@response)

        # check for emprty return result
        if @output.empty?
            @final_output = "Error"
        elsif !@output
            @final_output = "Error"
        else
             @final_output = @output[0]['AQI']
        end

        if @final_output == "Error"
            @api_color = "silver"
        elsif @final_output <= 50
            @api_color ="green"
            @api_description = "Good (0-50)"
        elsif @final_output >= 51 && @final_output <=100
            @api_color ="yellow"
            @api_description = "Moderate (51-100)"
        elsif @final_output >= 101 && @final_output <=150
            @api_color ="orange"
            @api_description = "Unhealthy for Sensitive Groups (USG) (101-150)"
        elsif @final_output >= 151 && @final_output <=200
            @api_color ="red"
            @api_description = "Unhealthy (151-200)"
        elsif @final_output >= 201 && @final_output <300
            @api_color ="purple"
            @api_description = "Very Unhealthy (201-300)"
        else @final_output >= 301 && @final_output <=500
            @api_color ="magenta"
            @api_description = "Hazardous 300-500)"

        end














      end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Ozone Health", root_path, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    </ul>
    <%= form_tag zipcode_path, :method => 'POST' do %>
    <div class="form-inline my-2 my-lg-0">
        <%= text_field_tag 'zipcode', nil, placeholder: "search zipcode", class: "form-control mr-sm-2" %>
        <%= submit_tag 'Search', class: "btn btn-outline-secondary my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/home/index.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%=@final_output %></h1>
  <p class="lead">This is the current air quality index for the 82007 zip code.</p>
  <hr class="my-4">
  <p><%= @api_description %></p>
  <br>
</div>

<br>

app/views/home/zipcode.html.erb
<div class="jumbotron <%= @api_color %>">
  <h1 class="display-4"><%=@final_output %></h1>
  <p class="lead">This is the current air quality index for the <%= @zip_query %> zip code.</p>
  <hr class="my-4">
  <p><%= @api_description %></p>
  <br>
</div>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ozone Health</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>